### ISSUE TITLE
yarn ng g @wishtack/schematics overrides directory structure.....

### ISSUE THREAD

**Issue by MHacker9404** [wishtack/wishtack-steroids#176]
When I do ng g @wishtack/schematics - the SCAM is created in my current working directory.  But if I do yarn ng....the SCAM is created at the app root level?

**Comment by yjaaidi** [comment]
Hi @MHacker9404,

This is the default behavior with `yarn` and `npm run`. They run commands with the project's root path as current working directory.

Do you think we should update the documentation and just mention `ng g` instead of `yarn ng g`?
 https://github.com/wishtack/wishtack-steroids/blob/97de15f63bfea09f73defd6b8be29bb18f736ab1/packages/schematics/README.md#L17

**Comment by yjaaidi** [comment]
Hi @MHacker9404 , I'm closing the issue due to inactivity.
Feel free to reopen an issue if needed.
Thanks
